# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
java_version=21

# Fabric
fabric_version=0.116.4+1.21.1
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.1.234
neoforge_version_range=[21.1,)
neoforge_loader_version_range=[4,)

# Testing
emi_version=1.1.24+1.21.1+neoforge
farmers_delight_version=1.21.1-1.3.2
clutter_no_more_version=2.0.7+1.21.1
create_version=6.0.10+mc1.21.1
sable_version=2.0.4+mc1.21.1
create_aeronautics_version=1.3.1+mc1.21.1
cloth_config_version=15.0.140
barehanded_version=1.6.6
reconnectible_chains_version=2.3.2
blueprint_version=8.1.1
gallery_version=2.0.1
clayworks_version=4.0.3

# Mod
mod_id=bbb
mod_name=Building But Better
mod_license=LGPL-3.0-or-later (code), ARR (assets)
mod_version=1.0.0
mod_group_id=com.crispytwig.bbb
mod_authors=crispytwig
mod_description=A mod that aims to bridge the gap between furniture mods and buildings mods, by adding a cohesive building structure that is not only beautiful, but also fun to use.
mod_issues=https://github.com/crispytwig/Building-But-Better/issues
