plugins {
    id 'net.neoforged.moddev'
}

repositories {
    maven {
        name = 'FabricMC'
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    compileOnly 'net.fabricmc:sponge-mixin:0.15.4+mixin.0.8.7'
    compileOnly 'io.github.llamalad7:mixinextras-common:0.4.1'
}

neoForge {
    neoFormVersion = neo_form_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
