plugins {
    id 'net.neoforged.moddev'
}

def generatedResources = project(':common').file('src/generated/resources')
def commonResources = project(':common').file('src/main/resources')

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }

    runs {
        configureEach {
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            gameDirectory = project.file('runs/server')
            programArgument '--nogui'
        }
        data {
            data()
            gameDirectory = project.file('runs/data')
            programArguments.addAll '--all',
                    '--mod', mod_id,
                    '--output', generatedResources.absolutePath,
                    '--existing', commonResources.absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly "maven.modrinth:emi:${emi_version}"
    runtimeOnly "maven.modrinth:emi:${emi_version}"
    compileOnly "maven.modrinth:farmers-delight:${farmers_delight_version}"
    runtimeOnly "maven.modrinth:farmers-delight:${farmers_delight_version}"
    compileOnly "maven.modrinth:clutter-no-more:${clutter_no_more_version}-neoforge"
    runtimeOnly "maven.modrinth:clutter-no-more:${clutter_no_more_version}-neoforge"
    runtimeOnly "maven.modrinth:create:${create_version}"
    runtimeOnly "maven.modrinth:sable:${sable_version}-neoforge"
    runtimeOnly "maven.modrinth:create-aeronautics:${create_aeronautics_version}"
    runtimeOnly "maven.modrinth:cloth-config:${cloth_config_version}+neoforge"
    runtimeOnly "maven.modrinth:reconnectible-chains:${reconnectible_chains_version}-${minecraft_version}-neoforge"
    runtimeOnly "maven.modrinth:barehanded:${barehanded_version}-neoforge"
    compileOnly "maven.modrinth:blueprint:${blueprint_version}"
    runtimeOnly "maven.modrinth:blueprint:${blueprint_version}"
    compileOnly "maven.modrinth:clayworks:${clayworks_version}"
    runtimeOnly "maven.modrinth:clayworks:${clayworks_version}"
    runtimeOnly "maven.modrinth:gallery:${gallery_version}"
}

sourceSets.main.resources {
    srcDir generatedResources.absolutePath
}